/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crossmoduleca;

import static crossmoduleca.Login.pswdinput;
import static crossmoduleca.usersdata.pswd;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import crossmoduleca.MySQLConection;
import javax.swing.JOptionPane;

/**
 *
 * @author luizaalbuquerque
 * 
 */
public class CrossmoduleGUI extends javax.swing.JFrame {
    
      Connection dbconn = null;
      PreparedStatement pst = null;
      ResultSet rs= null;
      
       public void login(){
          String query = "SELECT * FROM USERS WHERE username = '" + username + "' AND pswd = '" + pswd + "'";
          try {
              // this part is gonna check what was typed on the text field
              pst = dbconn.prepareStatement(query);
              pst.setString(1, txtUser.getText());
              pst.setString(2, txtPassword.getText());
               pst.setString(3, txtLoginSign.getText());
                pst.setString(4, txtPasswordLogin.getText());
              // the line under execute the query
              rs = pst.executeQuery();
              // Now gonna use If to ensure that user and password exist
              if (rs.next()){
                  
                  // if the 
                  Mainscreen Mainscreen = new Mainscreen();
                  Mainscreen.setVisible(true);
              }else{
                  JOptionPane.showMessageDialog(null,"user invalid");
              }
              
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
          }
          }
          
      
        public CrossmoduleGUI(){
        initComponents();
        dbconn = MySQLConection.dbconn();
        System.out.println(dbconn);
        
        if (dbconn != null ){
            lblStatus.setText("Connected");
        }else{
            lblStatus.setText("Not Connected");
        }
          
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtLoginSign = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LOGIN");

        jLabel2.setText("SIGN UP");

        jLabel3.setText("Username");

        jLabel4.setText("Username");

        jLabel5.setText("Password");

        jLabel6.setText("Password");

        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        btnLogin.setText("SIGN UP");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblStatus.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginBtn)
                    .addComponent(btnLogin))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblStatus)
                                .addComponent(jLabel6)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLoginSign)
                            .addComponent(txtPasswordLogin)
                            .addComponent(txtUser)
                            .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel2)))
                .addGap(66, 151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(loginBtn)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoginSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(31, 31, 31)
                .addComponent(lblStatus)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    
   //    variables
    public static String pswdinput;
    public static String username;
    public static String userAdmin;

    public static void loginCheck(String username, String pswd) throws SQLException {

        pswdinput = pswd;



//connecting DB

   
           // create a connection
           
          
            
    }
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        
       login();
        
        
              
    }//GEN-LAST:event_loginBtnActionPerformed
/*
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        // call the method
        login();

        try {

            //execute the query 
            //        checking username and password
            String query = "SELECT * FROM USERS WHERE username = '" + username + "' AND pswd = '" + pswd + "'";

            Statement stmt = null;
            ResultSet rs = null;
            Connection dbconn;
            dbconn = new MySQLConection().dbconn();
            stmt = dbconn.createStatement();
            rs = stmt.executeQuery(query);

            if (!rs.next()) {
                System.out.println("The user don't exits, to create a new account, fill in the following: ");

                Scanner scannerUser = new Scanner(System.in); //using scanner to store the user input

                System.out.print("Username: "); //check username

                String user = scannerUser.nextLine().toLowerCase(); // store username

                System.out.print("Password: "); //check password

                String pwd = scannerUser.nextLine().toLowerCase(); //store password

                System.out.print("(use a single letter) Gender: "); //check gender

                String gender = scannerUser.nextLine().toLowerCase(); //store gender

                System.out.print("(admin or regular) Usertype:"); //check usertype

                String usertype = scannerUser.nextLine().toLowerCase(); //store user type

                System.out.print("Fullname: "); //check fullname

                String userfullname = scannerUser.nextLine().toLowerCase(); //store full name

                System.out.print("use 1 for active and 0 for unactive: "); //check activity

                String useractive = scannerUser.nextLine().toLowerCase(); //store activity

                System.out.print("Phone: "); //check phone

                String phone = scannerUser.nextLine().toLowerCase(); //store phone

//                    creting the signup
                SingUp signup = new SingUp();
                signup.NewAccountWith(userfullname, user, pwd, usertype, gender, useractive, phone);

            }
        } catch (SQLException ex) {
            Logger.getLogger(CrossmoduleGUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnLoginActionPerformed
*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrossmoduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrossmoduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrossmoduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrossmoduleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrossmoduleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField txtLoginSign;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordLogin;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
